name: and_game
description: A dart package to append either & or and at the end of a List.
version: 1.0.0
homepage: https://github.com/piedcipher/and_game
repository: https://github.com/piedcipher/and_game
issue_tracker: https://github.com/piedcipher/and_game

environment:
  sdk: '>=2.14.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
